"use client";

import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { canLoadProtectedAdminData, useAdminAuth } from "@/components/admin/AdminAuthBoundary";
import { getRateCardValidationQueue, reviewRateCardDeliverable, type RateCardValidationItem } from "@/features/admin/ratecard-validations/service";

export default function RateCardValidationsPage() {
  const { state }=useAdminAuth(); const [items,setItems]=useState<RateCardValidationItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [notes,setNotes]=useState<Record<string,string>>({}); const [busy,setBusy]=useState<string|null>(null);
  const load=useCallback(async()=>{if(!canLoadProtectedAdminData(state))return;setLoading(true);try{setItems(await getRateCardValidationQueue());setError(null);}catch(e){setError(e instanceof Error?e.message:"Gagal memuat antrean.");}finally{setLoading(false);}},[state]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);
  const review=async(item:RateCardValidationItem,decision:"valid"|"invalid")=>{const note=(notes[item.id]||"").trim();if(decision==="invalid"&&!note){setError("Catatan wajib untuk keputusan invalid.");return;}const wording=decision==="valid"?"Tandai valid? UMKM masih harus menyetujui sebelum escrow dirilis.":"Tandai invalid? Creator akan diminta memperbaiki deliverable.";if(!window.confirm(wording))return;setBusy(item.id);try{await reviewRateCardDeliverable(item.id,decision,note);await load();}catch(e){setError(e instanceof Error?e.message:"Review gagal.");}finally{setBusy(null);}};
  return <div className="space-y-6 pb-12"><div className="rounded-3xl bg-[#0c172b] p-6 text-white"><h1 className="text-2xl font-black">Validasi Deliverable Rate Card</h1><p className="mt-2 text-sm text-slate-300">MVP manual. Tidak ada verifikasi otomatis Instagram atau TikTok. Keputusan valid hanya membuka persetujuan UMKM; tidak memindahkan dana sendiri.</p></div><div className="flex justify-end"><Button onClick={load} disabled={loading}>Segarkan</Button></div>{error&&<Card className="border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</Card>}{loading?<Card className="p-6 text-sm">Memuat antrean...</Card>:items.length===0?<Card className="p-6 text-sm">Tidak ada deliverable menunggu validasi.</Card>:items.map(item=><Card key={item.id} className="space-y-3 p-5"><div><p className="font-bold">{item.projectTitle} · Versi {item.version}</p><p className="text-xs text-muted-foreground">Order {item.orderId} · {item.source} · {item.submittedAt}</p></div><a className="block break-all text-sm text-blue-700 underline" href={item.evidenceUrl} target="_blank" rel="noreferrer">{item.evidenceUrl}</a>{item.notes&&<p className="text-sm">Catatan creator: {item.notes}</p>}<textarea value={notes[item.id]||""} onChange={e=>setNotes({...notes,[item.id]:e.target.value})} placeholder="Catatan review (wajib bila invalid)" className="min-h-20 w-full rounded border p-2 text-sm" maxLength={2000}/><div className="flex gap-2"><Button disabled={busy===item.id} onClick={()=>review(item,"valid")}>Tandai Valid</Button><Button variant="destructive" disabled={busy===item.id} onClick={()=>review(item,"invalid")}>Tandai Invalid</Button></div></Card>)}</div>;
}
